#! /bin/sh

echo "setting dotfile symlinks..."

# build symbolic links to dotfiles #############################################
if [ ! -e "$HOME/.vimrc" ]
then
    ln -s ~/dotfiles/vim/vimrc ~/.vimrc
else
    ln -sfn ~/dotfiles/vim/vimrc ~/.vimrc
fi

if [ ! -e "$HOME/.tmux.conf" ]
then
    ln -s ~/dotfiles/tmux/tmux.conf ~/.tmux.conf
else
    ln -sfn ~/dotfiles/tmux/tmux.conf ~/.tmux.conf
fi

if [ ! -e "$HOME/.gitconfig" ]
then
    ln -s ~/dotfiles/git/gitconfig ~/.gitconfig
else
    ln -sfn ~/dotfiles/git/gitconfig ~/.gitconfig
fi

if [ ! -e "$HOME/.gdbinit" ]
then
    ln -s ~/dotfiles/gdb/gdbinit ~/.gdbinit
else
    ln -sfn ~/dotfiles/gdb/gdbinit ~/.gdbinit
fi

if [ ! -e "$HOME/.dircolors" ]
then
    ln -s ~/dotfiles/terminalcolors/dircolors ~/.dircolors
else
    ln -sfn ~/dotfiles/terminalcolors/dircolors ~/.dircolors
fi

################################################################################
