" Vim Configuration File

" Pathogen Plugin Manager
execute pathogen#infect()

" Vundle Plugins ====================================================
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-fugitive'
Plugin 'Valloric/YouCompleteMe'
Plugin 'dusans/vim-hardmode'
Plugin 'arcticicestudio/nord-vim'
Plugin 'itchyny/lightline.vim'
Plugin 'lervag/vimtex'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
" ===================================================================

syntax on

" Colorscheme Nord ==================================================
"let g:nord_italic = 1
let g:nord_underline = 1
let g:nord_italic_comments = 1
"let g:nord_uniform_status_lines = 1
"let g:nord_comment_brightness = 12
let g:nord_uniform_diff_background = 1
let g:nord_cursor_line_number_background = 1
colorscheme nord

" set lightline color scheme nord
let g:lightline = { 'colorscheme': 'nord',  }
" ===================================================================

" Always show status-line
set laststatus=2

" spell checking
setlocal spell spelllang=en_us

" word completion
set complete+=kspell

" ==================== SEARCH =======================================
" search highlight
set hlsearch

" incremental search
set incsearch

" shortcut to mute search highlighting
nnoremap <silent> <C-n> :<C-u>nohlsearch<CR><C-l>
" ===================================================================

" ==================== FOLDING ======================================
set foldenable
set foldlevelstart=1
set foldnestmax=10
set foldmethod=syntax
set foldcolumn=4

" sh folding
let sh_fold_enabled=1

" zsh folding
let zsh_fold_enable=1
" ===================================================================
"
" 
" ==================== Language Specifics ===========================
"" C
let c_space_errors=1
let c_curly_error=1

" python
let python_highlight_all=1
" ===================================================================
"
" file encoding
set fileencodings=utf-8

" tab space
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab

" line numbers
set number relativenumber
set nu rnu
set cursorline

" disable arrow keys in vim mode
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Right> <NOP>
noremap <Left> <NOP>

" Enable Vim Hard Mode
autocmd VimEnter,BufNewFile,BufReadPost * silent! call HardMode()
nnoremap <leader>h <Esc>:call ToggleHardMode()<CR>

" changing focus of windows
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

" set text width
highlight OverLength ctermbg=DarkMagenta ctermfg=white guibg=#592929
match OverLength /\%120v.\+/

" ctags option
set tags=./tags;

" set nerd-tree like behavior as default when opening explorer mode (:E)
let g:netrw_liststyle=3
let g:netrw_altv=2

" use hidden buffers more liberally (without showing error messages)
set hidden

" map saving files
map <C-s> <esc>:w<CR>
imap <C-s> <esc>:w<CR>

" show invisibles
nmap <leader>l :set list!<CR>
set listchars=tab:▸\ ,eol:¬

" shared system clipboard
set clipboard=unnamed

" Use 256 colors (Use this setting only if your terminal supports 256 colors)
set t_Co=256

" Shortcut ,v opens vimrc file in a new tab when in normal mode
"let mapleader = ","
"nmap <leader>v :tabedit $MYVIMRC<CR>

" Latex Settings ====================================================

" REQUIRED. This makes vim invoke Latex-Suite when you open a tex file.
"filetype plugin on

" IMPORTANT: win32 users will need to have 'shellslash' set so that latex
" can be called correctly.
"set shellslash

" IMPORTANT: grep will sometimes skip displaying the file name if you
" search in a singe file. This will confuse Latex-Suite. Set your grep
" program to always generate a file-name.
"set grepprg=grep\ -nH\ $*

" OPTIONAL: This enables automatic indentation as you type.
"filetype indent on

" OPTIONAL: Starting with Vim 7, the filetype of empty .tex files defaults
" to 'plaintex' instead of 'tex', which results in vim-latex not being loaded.
" The following changes the default filetype back to 'tex':
"let g:tex_flavor='latex'

"let g:Tex_ViewRule_dvi = 'xdvi'
"let g:Tex_ViewRule_dvi = 'xdvi>/dev/null 2>/dev/null'
"let g:Tex_DefaultTargetFormat = 'pdf'
"let g:Tex_MultipleCompileFormats='pdf, aux'

" vim-latex pdf preview for mac
"let g:Tex_ViewRule_ps= 'open -a Preview'
"let g:Tex_ViewRule_pdf= 'open -a Preview'
" ===================================================================
